# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configuration
VAGRANT_API_VERSION = "2"
VM_BOX_UBUNTU = "ubuntu/jammy64"  # Ubuntu 22.04
VM_BOX_KALI = "kalilinux/rolling"

# Network config
HOST_ONLY_NETWORK = "192.168.56.0"
ELK_SERVER_IP = "192.168.56.10"
UBUNTU_CLIENT_IP = "192.168.56.20"
WINDOWS_CLIENT_IP = "192.168.56.30"
KALI_ATTACKER_IP = "192.168.56.50"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  
  # Global configuration
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: false
  
  # Configure hostmanager plugin
  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = false
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
  end

  #
  # ELK Server - The Brain
  #
  config.vm.define "elk-server" do |elk|
    elk.vm.box = VM_BOX_UBUNTU
    elk.vm.hostname = "elk-server"
    
    # Network
    elk.vm.network "private_network", ip: ELK_SERVER_IP
    
    # Resources - Elasticsearch is hungry
    elk.vm.provider "virtualbox" do |vb|
      vb.name = "elk-siem-server"
      vb.memory = 6144  # 6GB RAM minimum
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    
    # Provisioning - Install Python for Ansible
    elk.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3 python3-pip
    SHELL
  end

  #
  # Ubuntu Client - The Victim
  #
  config.vm.define "ubuntu-client" do |client|
    client.vm.box = VM_BOX_UBUNTU
    client.vm.hostname = "ubuntu-client"
    
    # Network
    client.vm.network "private_network", ip: UBUNTU_CLIENT_IP
    
    # Resources
    client.vm.provider "virtualbox" do |vb|
      vb.name = "elk-siem-client"
      vb.memory = 2048
      vb.cpus = 1
    end
    
    # Provisioning
    client.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3 python3-pip
    SHELL
  end

  #
  # Kali Attacker - The Chaos
  #
  config.vm.define "kali-attacker" do |kali|
    kali.vm.box = VM_BOX_KALI
    kali.vm.hostname = "kali-attacker"
    
    # Network
    kali.vm.network "private_network", ip: KALI_ATTACKER_IP
    
    # Resources
    kali.vm.provider "virtualbox" do |vb|
      vb.name = "elk-siem-attacker"
      vb.memory = 2048
      vb.cpus = 2
      vb.gui = false  # Headless, we're not savages
    end
    
    # Provisioning
    kali.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3 python3-pip
      # Install attack tools (if not already in Kali)
      apt-get install -y hydra nmap sqlmap nikto
    SHELL
  end
  
  #
  # Windows Client (Optional) - The Enterprise
  #
  # Uncomment if you want Windows logging
  # config.vm.define "windows-client" do |win|
  #   win.vm.box = "gusztavvargadr/windows-10"
  #   win.vm.hostname = "windows-client"
  #   
  #   win.vm.network "private_network", ip: WINDOWS_CLIENT_IP
  #   
  #   win.vm.provider "virtualbox" do |vb|
  #     vb.name = "elk-siem-windows"
  #     vb.memory = 4096
  #     vb.cpus = 2
  #     vb.gui = false
  #   end
  # end

end
